### ISSUE TITLE
Added legacy to repo name, propose set to private archive or deletion

### ISSUE THREAD

**Issue by KemingHe** [devosu/legacy-research-mentorship-frontend#2]
@BennettGN @GulkoA @trev-org04 Hi, since in Monday 0513's meeting we decided to fork the Event Feed project as the new frontend. Should we archive or delete this soon-to-be legacy repo? Let's discuss and share your thoughts below:

**Comment by GulkoA** [comment]
let's archive it, I see no reason to delete it yet. Just make sure it is clear for junior devs where to contribute starting next week
